env: standard
runtime: nodejs10
service: jaybisa-website

handlers:
  - url: .*
    static_files: build/index.html
    upload: build/index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
